config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'

  resources :landing

  resources :profile, only: :index

  resources :agencies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.role = "traveller"

      if  auth.provider == "facebook"
        response = RestClient.get "https://graph.facebook.com/v2.7/#{auth[:uid]}?fields=last_name,first_name&access_token=#{auth[:credentials][:token]}"
        response = JSON.parse(response)
        user.first_name = response["first_name"]
        user.last_name = response["last_name"]
      elsif  auth.provider == "google_oauth2"
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_role?(role)
    self.role == role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/concerns/agencies_controller.rb
class AgenciesController < ApplicationController
  skip_before_action :authenticate_user!, only: :new

  def new
  end

end

app/controllers/concerns/users_controller.rb
class UsersController < ActionController::Base

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_filter :ensure_login

  skip_before_action :authenticate_user!, only: :index
  layout "landing"
  def index
  end


  private
  def ensure_login
    if current_user
      redirect_to profile_index_path
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) #Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    if current_user.has_role?("traveller")
      render "traveller"
    elsif current_user.has_role?("agency")
      render "agency"
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :role, :agency_name, :phone_2, :about_agency, :location, :website ])
      super
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  skip_before_filter :verify_authenticity_token, :only => :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agencies/new.html.haml
.row#agency-signup
  .col-md-4
  .col-md-4
    .card-group-template
      .signup-div
        = form_for(User.new, as: :user, url: registration_path(:user)) do |f|
          .section-one
            %h1 Create an Agency Account
            %p
              Not and Agency? Continue to
              %span
                =link_to "Bckets", root_path
          .section-two
            = f.email_field :email,  :placeholder => "Email *", :required => true, class: "form-control"
            = f.password_field :password,  :placeholder => "Password *",  :required => true, class: "form-control"
            = f.text_field :agency_name,  :placeholder => "Agency Name *",  :required => true, class: "form-control"
            .row
              .col-md-6
                = f.text_field :phone,  :placeholder => "Phone #1 *",  :required => true, class: "form-control"
              .col-md-6
                = f.text_field :phone_2,  :placeholder => "Phone #2", class: "form-control"
            = f.text_area :about_agency,  :placeholder => "About Your Agency", class: "form-control"
            = f.text_field :location,  :placeholder => "Location", class: "form-control"
            = f.text_field :website,  :placeholder => "Website", class: "form-control"
            = f.hidden_field :role,  value: "agency"
          .section-three
            %button.btn.btn-primary{:type => "submit"} Sign up
            %p
              By signing up, I agree to Bckets’
              %span Terms of Service
        .section-four
          .row
            .col-md-7
              %p Already have an account?
            .col-md-5
              %button.btn.btn-primary Log in
  .col-md-4

app/views/landing/hey.html.haml
hey

app/views/landing/index.html.haml
Hello World

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bckets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
    <%= insert_paloma_hook %>
  </body>
</html>